# Generated by Django 2.1.1 on 2018-09-10 08:35

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=books.models.upload_location)),
                ('book_name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Computer Science', 'Computer Science'), ('Information Science', 'Information Science'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronic and Communication', 'Electronic and Communication'), ('Medical Electronics', 'Medical Electronics'), ('Instrumentaion Engineering', 'Instrumentaion Engineering'), ('Architecture', 'Architecture')], max_length=100)),
                ('sem', models.PositiveIntegerField(choices=[(1, 1), (3, 3), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
